### ISSUE TITLE
Replace poster with black background when playing clips

### ISSUE THREAD

**Issue by racepi** [cf73/Race2#102]
Clips which are a different aspect ratio such as http://racepi.s3-website-us-west-1.amazonaws.com/clips/victoria-robinson-shares-how-she-uses-her-favorite-clip-on-redlining-in-her-teaching play in a smaller player on top of the poster frame.

This can be 'fixed' by replacing the poster frame with a black background when the clip is playing, giving the impression of a correct-aspect-ratio clip with wide black bars either side of the actual content.

**Comment by cf73** [comment]
@eugenehp please fix after the S3 and interview related content cards

**Comment by eugenehp** [comment]
@cf73 please attach screenshots of how you see it on your end. Thanks.

**Comment by cf73** [comment]
![image](https://user-images.githubusercontent.com/25471024/45279690-efc0f480-b49f-11e8-95e8-f1427ff32b8f.png)
@eugenehp if this takes more than 20 mins, don't do it (or let me know first)

**Comment by cf73** [comment]
also, background should be #222222 (softblack)

**Comment by eugenehp** [comment]
<img width="624" alt="screen shot 2018-09-10 at 10 02 13" src="https://user-images.githubusercontent.com/1857263/45312319-9dec8e80-b4e0-11e8-9511-c978c9265974.png">
<img width="653" alt="screen shot 2018-09-10 at 10 02 08" src="https://user-images.githubusercontent.com/1857263/45312320-9e852500-b4e0-11e8-95eb-49ecd1bee558.png">

fixed.
