### ISSUE TITLE
handouts (in teaching page) doesn't pull from CMS 'handouts' content type

### ISSUE THREAD

**Issue by cf73** [cf73/Race2#47]
it just appears to be hardcoded

**Comment by eugenehp** [comment]
what graphic structure has this data?

**Comment by cf73** [comment]
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/25471024/44416403-c831d880-a540-11e8-86d1-beedf3d4b663.png">

**Comment by cf73** [comment]
I've added the query and updated the UI to show this, but we need to build a new layer to present the actual handout content. Will create new scoped issue for this.
