### ISSUE TITLE
typekit is not working properly, but did in previous build

### ISSUE THREAD

**Issue by cf73** [cf73/Race2#50]
see http://condescending-varahamihira-a50f36.netlify.com -- it works there, and I've double-checked the typekit settings, so something is wrong in this build

**Comment by eugenehp** [comment]
I haven't really changed anything about typekit in my recent commits. have you tried incognito mode?
what was the last commit # that worked for you?

**Comment by cf73** [comment]
have tried across numerous computers, both platforms, in incognito with cache disabled etc., and the content team are also seeing the same with no fonts.
comparing the build that works (http://condescending-varahamihira-a50f36.netlify.com) to the current build, the only difference seems to be that the typekit id is in index.js in the old build, and in layout.js in the new one. typekit may be particular about being at the 'root' file...?

**Comment by cf73** [comment]
changed design, no longer an issue
