### ISSUE TITLE
all 'filed under' text has redundant naming

### ISSUE THREAD

**Issue by cf73** [cf73/Race2#77]
e.g. "Science: Pseudoscience" should be just "Pseudoscience"

and "Racial Classification: Changing Categories" should be just "Changing Categories"

It's not clear to me where these first parts of the name are coming from, but in any case we should strip them out. The second parts are the subthemes, which is all we should show in the 'filed under' sections.

**Comment by eugenehp** [comment]
it comes from Drupal.
