### ISSUE TITLE
Build About page and its children pages

### ISSUE THREAD

**Issue by cf73** [cf73/Race2#85]
See About Page in design file.

The main 'About' page spawns several simple children pages:
- an 'Episode' page for each episode (i.e. a template)
- an 'Episode Credits' page for each episode (i.e. a template)
- a 'Credits and Founders' page for the series (not really a template, as it's a one-off page)
- an 'Episode Transcript' page for each episode (i.e. a template)

**Comment by cf73** [comment]
Query for Critic Quote (at top of About Page)
`{allNodeCriticQuote {
  edges {
    node {
      title
      field_critic_quote {
        processed
      }
    }
  }
}}`

**Comment by cf73** [comment]
Query for the Statement from the Executive Producer title and body text:
`{allTaxonomyTermAboutTheFilmPage {
  edges {
    node {
      id
      field_updated_ep_statement_title {
        processed
      }
      field_updated_ep_statement {
        processed
      }
    }
  }
}}`

**Comment by cf73** [comment]
Query for the Episode title and Episode Synopsis text:
`{allNodeSynopsis {
  edges {
    node {
      title
      field_episode_synopsis {
        processed
      }
    }
  }
}}`

**Comment by cf73** [comment]
Query for Episode Credits
`{allNodeEpisodeCredits {
  edges {
    node {
      title
      field_episode_credits {
        processed
      }
      field_episode_copy {
        processed
      }
    }
  }
}}`

**Comment by cf73** [comment]
Query for Episode Transcript
`{allNodeTranscript {
  edges {
    node {
      title
      body {
        processed
      }
      field_cop {
        processed
      }
    }
  }
}}`

**Comment by cf73** [comment]
Query for Series Production Credits:
`{allTaxonomyTermAboutTheFilmPage {
  edges {
    node {
		      field_series_production_credits {
            processed
          }
    }
  }
}}`

**Comment by eugenehp** [comment]
where do I get episode info? @cf73

**Comment by cf73** [comment]
not sure what you mean @eugenehp , it's all in the queries above..?

**Comment by eugenehp** [comment]
@cf73 ok, I'll see if it will be enough to use just these queries.

**Comment by cf73** [comment]
@eugenehp you also have the drupal access if needed (hope not needed!)

**Comment by eugenehp** [comment]
I hope so too.

**Comment by eugenehp** [comment]
<img width="842" alt="screen shot 2018-09-01 at 08 12 34" src="https://user-images.githubusercontent.com/1857263/44947231-d0024000-adbe-11e8-9440-4233c9583929.png">

where do I get this quote from? @cf73

**Comment by eugenehp** [comment]
<img width="635" alt="screen shot 2018-09-01 at 08 12 58" src="https://user-images.githubusercontent.com/1857263/44947234-dbee0200-adbe-11e8-81a8-719244afea0f.png">
 and this text

**Comment by cf73** [comment]
@eugenehp the critic quote you asked about is in the second comment on this issue

**Comment by cf73** [comment]
@eugenehp and the one for the statement from executive producer is right under it, third comment on this issue.

**Comment by eugenehp** [comment]
![screen shot 2018-09-01 at 16 37 57](https://user-images.githubusercontent.com/1857263/44950766-68231800-ae05-11e8-931d-bbd1030acd84.png)

getting wrong data inside the credits.

```
allNodeEpisodeCredits {
      edges {
        node {
          title
          field_episode_credits {
            processed
          }
          field_episode_copy {
            processed
          }
        }
      }
    }
```

**Comment by eugenehp** [comment]
![screen shot 2018-09-01 at 16 41 19](https://user-images.githubusercontent.com/1857263/44950788-e089d900-ae05-11e8-8224-f35f6d78c5e1.png)

also CMS data does not match what you have within the design 
@cf73

**Comment by cf73** [comment]
@eugenehp here's the updated query for the three parts of the Episode page i mentioned, PLUS the new query for the 'explore' (related subthemes). I will post similar new queries for the other episodes after this.

{taxonomyTermEpisodeOnePage {
  field_episode_one_title {
    processed
  }
  field_episode_one_synopsis {
    processed
  }
  field_episode_one_transcript {
    processed
  }
  field_episode_one_credits {
    processed
  }
  relationships {
    field_explore_subthemes_related {
      NOT SURE WHAT THIS BIT IS
    }
  }
}}

**Comment by cf73** [comment]
@eugenehp Here are the two other episode queries. NOTE: I've added a new field, 'Episode Title', which is where you should pull any instances of the episode title from. Not sure where it was coming from before, but get it from here now.

{taxonomyTermEpisodeTwoPage {
  field_episode_two_ {
    processed
  }
  field_episode_two_synopsis {
    processed
  }
  field_episode_two_transcript {
    processed
  }
  field_episode_two_credits {
    processed
  }
  relationships {
    field_explore_subthemes_re2 {
      NOT SURE WHAT THIS BIT IS
    }
  }
}}



{taxonomyTermEpisodeThreePage {
  field_episode_three_title {
    processed
  }  
  field_episode_three_synopsis {
    processed
  }
  field_episode_three_ {
    processed
  }
	field_episode_three_credits {
    processed
  }
  relationships {
    field_explore_subthemes_re3 {
      NOT SURE WHAT THIS BIT IS
    }
  }
}}

**Comment by eugenehp** [comment]
![screen shot 2018-09-01 at 22 56 55](https://user-images.githubusercontent.com/1857263/44952684-5740c980-ae3a-11e8-82a2-9c77bce60cef.png)
![screen shot 2018-09-01 at 22 56 53](https://user-images.githubusercontent.com/1857263/44952685-5740c980-ae3a-11e8-9659-2163c84196fa.png)

got above queries reused to generate this pages, spent extra hour because of restructuring of the queries.

**Comment by eugenehp** [comment]
<img width="184" alt="screen shot 2018-09-01 at 23 00 25" src="https://user-images.githubusercontent.com/1857263/44952699-d504d500-ae3a-11e8-8c0a-3ff917b1b1c0.png">

@cf73 where do I pull these from?

**Comment by cf73** [comment]
@eugenehp the bit at the bottom of each of the new queries I pasted above,

relationships {
field_explore_subthemes_re3 {
NOT SURE WHAT THIS BIT IS
}
etc.

**Comment by eugenehp** [comment]
What are those? Articles or subthemes or other entities?

**Comment by cf73** [comment]
@eugenehp how did it take a whole hour to swap out some queries? should have taken a matter of minutes. we don't have this kind of money on this project, and there's still other stuff to do.

**Comment by cf73** [comment]
@eugenehp they're subthemes. 

the journey is: from the episode page, you can explore related subthemes.

**Comment by cf73** [comment]
@eugenehp small issue, but need to fix (lower priority though): the critic quotes on the About page are supposed to be in randomized order upon page load, so you don't always see the same one first.
