### ISSUE TITLE
Home page revamp

### ISSUE THREAD

**Issue by cf73** [cf73/Race2#86]
See 'Home page' in design file
[work in progress, but will feature:
- a prominent CTA sending people to the themes collection page
- the video clip of john a powell introducing the site and film
- a large logo (to be provided) over the main image
- a tagline for the site, pulled from the CMS
- possibly some other minor stuff, e.g. select 'what the critics say' quotes]

**Comment by cf73** [comment]
Query for summary tagline ('An online companion to the award-winning documentary series'):
`{allTaxonomyTermHomePage {
  edges {
    node {
      field_site_summary_tagline {
        processed
      }
    }
  }
}}`

**Comment by cf73** [comment]
Query for john a. powell clip large text (see design file):

`{allTaxonomyTermHomePage {
  edges {
    node {
      field_text_under_john_a_powell_v {
        processed
      }
    }
  }
}}`

**Comment by eugenehp** [comment]
This one gives me not full information on some cases.

**Comment by cf73** [comment]
Query for Home page main image:
`{allTaxonomyTermHomePage {
  edges {
    node {
      relationships {
        field_home_page_top_image {
          localFile {
            publicURL
          }
        }
      }
    }
  }
}}`
