### ISSUE TITLE
Replace the 'subjects' fake tags in the lesson plans with real tags pulled from the CMS

### ISSUE THREAD

**Issue by cf73** [cf73/Race2#88]
These should trigger the tag cloud overlay, like any other tag.
Most lesson plans will not have tags, so I'll create some for testing tonight on "Just an Environment or a Just Environment? Racial Segregation and Its Impacts"

**Comment by eugenehp** [comment]
@cf73 not clear what should be done here. what's the source of this data? `graphql` query example?

**Comment by cf73** [comment]
@eugenehp i'm not sure what the last part of this is, but it should be same as the other tags used in the site, so you'll likely be able to figure it out as you get familiar with the tagcloud
```
{
allNodeLessonPlan {
  edges {
    node {
      relationships {
        field_subject_tags {
          
        }
      }
    }
  }
}
}
```

**Comment by cf73** [comment]
@eugenehp this doesn't seem to be integrated with the tagcloud -- the tags show up, but are not clickable.

**Comment by eugenehp** [comment]
![screen shot 2018-08-31 at 19 25 05](https://user-images.githubusercontent.com/1857263/44941504-96481f80-ad53-11e8-942c-4d08cf4fa5e2.png)
