### ISSUE TITLE
related content cards don't show up in interviews template

### ISSUE THREAD

**Issue by cf73** [cf73/Race2#91]
@eugenehp related content should show up in interviews template sidebar; appears to be a bug.

**Comment by eugenehp** [comment]
Apparently data exists only in this interview:
https://github.com/cf73/Race2/issues/102

![screen shot 2018-09-10 at 10 02 59](https://user-images.githubusercontent.com/1857263/45312411-d68c6800-b4e0-11e8-88e8-da685dce6087.png)
![screen shot 2018-09-10 at 10 03 01](https://user-images.githubusercontent.com/1857263/45312415-db511c00-b4e0-11e8-8cf8-4a93b4870ce7.png)

**Comment by cf73** [comment]
@eugenehp there's a bug here: interview cards don't show up, e.g. see http://localhost:8000/interviews/interview-with-dalton-conley -- which should feature these interviews in the related content section:
Interview with Nancy DiTomaso
Interview with Melvin Oliver
Interview with john a. powell

Please fix ASAP
